In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
#Import the data
data = pd.read_csv("dataset.csv")
data.head(5)

,site,form,method=post,method=get,script,javascripts,iframe,applet,frame,type=submit,...,length,At Sign,Forward Slashes,www Present,periods,dashes,underscores,number of digits,has ASCII,valid
0,https://coolcup795.weebly.com/blog/der-seltsam...,0,0,0,26,14,3,0,0,0,...,64,0,4,0,2,0,0,3,0,0
1,https://office365.auto1.casb.beta.forcepointgo...,0,0,0,10,7,0,0,0,23,...,868,0,13,14,5,0,0,4,19,0
2,https://login-live-com.office365.auto1.casb.be...,0,0,0,3,2,0,0,0,0,...,137,0,3,2,6,2,0,4,2,0
3,https://login-live-com.office365.auto1.casb.be...,0,0,0,14,4,0,0,0,0,...,84,0,3,1,6,2,0,4,1,0
4,https://bestyup786.weebly.com/,0,0,0,34,13,40,0,0,0,...,30,0,3,0,2,0,0,3,0,0

In [3]:
#drop "site" column
data = data.iloc[: , 1:]
data.head(5)

,form,method=post,method=get,script,javascripts,iframe,applet,frame,type=submit,email,...,length,At Sign,Forward Slashes,www Present,periods,dashes,underscores,number of digits,has ASCII,valid
0,0,0,0,26,14,3,0,0,0,1,...,64,0,4,0,2,0,0,3,0,0
1,0,0,0,10,7,0,0,0,23,61,...,868,0,13,14,5,0,0,4,19,0
2,0,0,0,3,2,0,0,0,0,0,...,137,0,3,2,6,2,0,4,2,0
3,0,0,0,14,4,0,0,0,0,4,...,84,0,3,1,6,2,0,4,1,0
4,0,0,0,34,13,40,0,0,0,2,...,30,0,3,0,2,0,0,3,0,0

In [4]:
#data types of each column
data.dtypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2227 entries, 0 to 2226
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   form              2227 non-null   int64
 1   method=post       2227 non-null   int64
 2   method=get        2227 non-null   int64
 3   script            2227 non-null   int64
 4   javascripts       2227 non-null   int64
 5   iframe            2227 non-null   int64
 6   applet            2227 non-null   int64
 7   frame             2227 non-null   int64
 8   type=submit       2227 non-null   int64
 9   email             2227 non-null   int64
 10  password          2227 non-null   int64
 11  button            2227 non-null   int64
 12  length            2227 non-null   int64
 13  At Sign           2227 non-null   int64
 14  Forward Slashes   2227 non-null   int64
 15  www Present       2227 non-null   int64
 16  periods           2227 non-null   int64
 17  dashes            2227 non-null   int64
 18  underscores       2227 non-null   int64
 19  number of digits  2227 non-null   int64
 20  has ASCII         2227 non-null   int64
 21  valid             2227 non-null   int64
dtypes: int64(22)
memory usage: 382.9 KB

In [5]:
# convert "valid" column into categorical
data['valid'] = pd.Categorical(data.valid)
data.dtypes

form                   int64
method=post            int64
method=get             int64
script                 int64
javascripts            int64
iframe                 int64
applet                 int64
frame                  int64
type=submit            int64
email                  int64
password               int64
button                 int64
length                 int64
At Sign                int64
Forward Slashes        int64
www Present            int64
periods                int64
dashes                 int64
underscores            int64
number of digits       int64
has ASCII              int64
valid               category
dtype: object

In [6]:
# split the data
X = data.loc[ : , data.columns != 'valid']
y = data['valid']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.99, random_state=42)

In [7]:
#defining the model
clf = RandomForestClassifier(max_depth=2, random_state=0)
#fitting the model
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [8]:
# model prediction
y_pred = clf.predict(X_test)

In [9]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.04      0.08       595
           1       0.74      1.00      0.85      1610

    accuracy                           0.74      2205
   macro avg       0.75      0.52      0.47      2205
weighted avg       0.75      0.74      0.64      2205

In [10]:
print(confusion_matrix(y_test, y_pred))

[[  26  569]
 [   8 1602]]

In [11]:
import pickle

In [12]:
with open ('model_pickle', 'wb') as f:
    pickle.dump(clf, f)